### ISSUE TITLE
Script errors out due to no SetLineWidth attribute

### ISSUE THREAD

**Issue by trholding** [diorcety/KiBlenderCad#3]
This is an awesome piece of software. I have been looking for something like this for a long time.

I get the following error:

MainThread - __main__ - ERROR - 'PCB_PLOT_PARAMS' object has no attribute 'SetLineWidth'

Do you know where to fix this?

I use KiCad 6.0.5 on linux.

**Comment by diorcety** [comment]
Seems that KitKit had the same issue: https://github.com/yaqwsx/KiKit/pull/88 solved by this commit: 
https://github.com/yaqwsx/KiKit/commit/0d08b2ff390a9c781cd9bdb09845e76e24e5d777
Can you try this fix and do a PR?

**Comment by diorcety** [comment]
Replacing setLineWidth by SetSketchPadLineWidth and using https://pypi.org/project/pcbnewTransition/ by replacing 
`import pcbnew` by `from pcbnewTransition import pcbnew`

**Comment by trholding** [comment]
Closing as it is not relevant for current version.
